### PR TITLE
Document phone number extension handling

### LINKED ISSUE #581: Extension information is lost during serialization
Firstly, thanks for an awesome library!

It looks to me like the extension information is lost when using Django's built in serialization. We only use this for loading our test database, but it was surprising when the extension's didn't survive reloading the data.

After a little bit of investigation, I think fixing this should be pretty straight forwards, we would just need to implement `value_to_string()` for the field with one of the lossless serialization formats and then make sure the the `to_python()` function can handle it properly.

https://docs.djangoproject.com/en/4.2/howto/custom-model-fields/#converting-field-data-for-serialization

If the contribution is welcome, I might be interested in adding this fix. Thanks again!

### PR DESCRIPTION
**Pull request by francoisfreitag**
Closes #581

### CODE REVIEW

**Comment by francoisfreitag** [comment]
@stefanfoulis do you remember why E.164 is the default over E.123 (INTERNATIONAL)?

**Comment by stefanfoulis** [comment]
> @stefanfoulis do you remember why E.164 is the default over E.123 (INTERNATIONAL)?
I don't know. :-/

**Comment by francoisfreitag** [comment]
I see. It might be a good idea to transition to the `INTERNATIONAL` format by default. I’ll start the deprecation in the upcoming weeks, unless someone is concerned with changing the default?

**Comment by francoisfreitag** [comment]
I started looking at changing the default. I don’t think it’s worth the hassle. I assume most projects don’t use extensions, and the `INTERNATIONAL` representation is slightly different:

```
>>> str(phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL))
'+44 20 8366 1177'
>>> str(phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.E164))
'+442083661177'
```

The added spaces are sure to break code for someone, who doesn’t care about extensions at all. Unless there’s strong support for changing the default, it’ll stay as `E164`.

**Pull request merged**
