### PR TITLE
Add a DB converter for the model field

### PR DESCRIPTION
**Pull request by francoisfreitag**
#558

### CODE REVIEW

**Comment by kalekseev** [comment]
This is a breaking change, would be better to release it in v8...

**Comment by francoisfreitag** [comment]
Oops, that’s right. Sorry for the trouble! I’ll update the release note text to highlight that.

**Comment by chris-erickson** [comment]
How would we get the old behavior back?

**Comment by francoisfreitag** [comment]
Depending on what you expect, I would say either:
- call `str()` on the `PhoneNumber` object (or the property for a specific format, such as [`.as_international`](https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_international), [`.as_e164`](https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#phonenumber_field.phonenumber.PhoneNumber.as_e164), ...)
- subclass the `phonenumber_field.modelfields.PhoneNumberField` and implement `to_python()` as     
  ```python
    def to_python(self, value):
        return value
   ```

**Comment by Neumsy** [comment]
> * subclass the `phonenumber_field.modelfields.PhoneNumberField` and implement `to_python()` as
>   ```python
>     def to_python(self, value):
>         return value
>   ```

When using this method, shouldn't the suggestion be to override the from_db_value method?  The calling to_python method is not part of the class inheritance, so overriding it in the class doesn't produce the desired outcome.

```python
    def from_db_value(self, value, expression, connection):
        return str(value)
```

**Pull request merged**
