### PR TITLE
Fixed typo in Hebrew translation

### PR DESCRIPTION
**Pull request by ari-gen-x**
This is really embarrassing, but I realized I made a typo in my initial contribution... :(

Here's a fix - sorry for the trouble.

### CODE REVIEW

**Comment by thedrow** [comment]
I didn't notice it when merging. It's all good.

**Comment by ari-gen-x** [comment]
Thanks.

Do you know when the next release is planned for?

**Comment by thedrow** [comment]
I'm not very active on this repo anymore so no sorry.

**Comment by ari-gen-x** [comment]
Understood, thanks anyway.

**Pull request merged**
