### PR TITLE
add missing Dutch translation

### PR DESCRIPTION
**Pull request by thijskramer**
I've added a missing translation string to the Dutch translations.

### CODE REVIEW

**Comment by francoisfreitag** [comment]
Sweet! Thank you :grin:

**Comment by francoisfreitag** [comment]
It’ll be a few weeks before the next release. I’m aiming at a 7.0.0 with some significant changes to the library.
Ideally https://github.com/stefanfoulis/django-phonenumber-field/pull/529 and the merged commits https://github.com/stefanfoulis/django-phonenumber-field/commit/d8c02478aca27f42fbfe98f606f91df7a1da6a94 and https://github.com/stefanfoulis/django-phonenumber-field/commit/290e82b9229db3f1833a150f2e32f18405205ff3.

If you need the translations sooner, please let me know and I’ll make a 6.5.0 release.

**Comment by thijskramer** [comment]
How many weeks are 'a few weeks'? If you plan on to release 7.0.0 within 2 or 3 weeks I can wait. If 7.0.0 takes longer I would kindly ask you to release a 6.5.0 release, if that isn't too much hassle! 

Anyhow, thanks for your very quick merge and reply! 🚀

**Comment by francoisfreitag** [comment]
I’ll aim for a release by the end of next week (September 16th). If not, I’ll cut a 6.5.0, it should be trivial.

**Pull request merged**
