### PR TITLE
Update widgets.py

### PR DESCRIPTION
**Pull request by behltazor**
Correction proposed in #214 issue (decompress wasn't keeping track of the leading zeroes)

### CODE REVIEW

**Comment by stefanfoulis** [comment]
Is this so that leading `0` are consistently removed?

The import seems to be missing.

**Comment by stefanfoulis** [comment]
I'm closing this PR for now. Please re-open if you still think this is an issue.

**Comment by behltazor** [comment]
Hi, sorry for the huge delay for an answer.
Yes it was missing the leading zero, I assume is a problem related only to Italian house number, but it would be nice if it can be solved.
Can you please point me out how to reopen the pull request?

**Comment by behltazor** [comment]
Hi, i think i do not have the permission to reopen the PR @stefanfoulis .

**Comment by stefanfoulis** [comment]
🤔 weird.
Ok, I'll re-open it.

**Comment by behltazor** [comment]
Thanks, i've added the missing import.

**Comment by jdufresne** [comment]
Could a test be added to demonstrate the change?

**Comment by behltazor** [comment]
Well, it is a frontend Django form problem when the PhoneNumberField has an initial number (landline with leading zero), so i'm not sure how to do so.

**Comment by behltazor** [comment]
@stefanfoulis 
Hi, is there any chance to sort things out?

**Comment by stefanfoulis** [comment]
LGTM. I'll fix the formatting (black, isort, flake8) separately. Something may be off with out config there.

**Pull request merged**
