### PR TITLE
Add the new locale HY

### PR DESCRIPTION
**Pull request by melikyan-a**
HY (Armenian)

### CODE REVIEW

**Comment by stefanfoulis** [comment]
This pull request **fixes 1 alert** when merging 4b4f102cbe2945e423f2c1cfefc7dc6c5a7427f1 into fbec5079fb453040e2568c81eec73017310aaa9a - [view on LGTM.com](https://lgtm.com/projects/g/stefanfoulis/django-phonenumber-field/rev/pr-d7b644f31dcc903f78b9a9cdd62e92e1723d9ad9)

**fixed alerts:**

* 1 for Special method has incorrect signature

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jdufresne** [comment]
Thanks @melikyan-a but I think there was a mistake opening the PR. I don't see your new commit and the target branch should be master.

**Comment by melikyan-a** [comment]
> Thanks @melikyan-a but I think there was a mistake opening the PR. I don't see your new commit and the target branch should be master.

Oh, sorry!
I did it.

**Comment by jdufresne** [comment]
Closing in favor of #317

**Pull request closed without merging**
